### ISSUE TITLE
Find and update external repository ID

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-migrate#1]
Drone 1.0 stores the external repository ID (e.g. from GitHub) in the database so that we can detect repository name changes. When you migrate repositories we create a dummy external ID. This temporary ID needs to be replaced with the actual ID.

This means we need to pass your source code management URL (e.g. https://github.com) and driver (i.e. github, gogs, gitea, gitlab, etc) to the migration utility. With this information, we should be able to make API calls to the source code management system to find and update the repository id.

I started work on this capability here:
https://github.com/drone/drone-migrate/blob/master/migrate/repos.go#L96

What is currently missing from my implementation are:

1. the client needs to be created with the correct driver and url
2. we should pass the user credentials to the client (via context)

**Comment by trevorriles** [comment]
Is this the last piece needed for this migration tool to work?

**Comment by bradrydzewski** [comment]
actually I completed this task. Currently the migration utility handles:

1. users
2. repositories
3. permissions
4. secrets
5. registry credentials

It does not yet handle:

1. build data
2. build steps
3. build logs

**Comment by bradrydzewski** [comment]
I created separate issues for the above items, and will close this particular issue.
